### ISSUE TITLE
Error during building api.

### ISSUE THREAD

**Issue by phreakus** [codexgigassys/codex-backend#1]
When I execute "sudo docker-compose up" command, httpd and db execute normally, but during building api some error is occured.
- OS : Ubuntu 16.04 LTS
- Python : 2.7.12
- Error message is like below.
  **Errors were encountered while processing:**
  python-support
  python-cairo
  python-gtk2
  python-glade2
  python-ndg-httpsclient
  **E: Sub-process /usr/bin/dpkg returned an error code (1)**
  **ERROR: Service 'api' failed to build:** The command '/bin/sh -c apt-get clean && apt-get update -qq && apt-get install -y build-essential libpq-dev python-hachoir-metadata p7zip-full libffi-dev libssl-dev python-dev libfuzzy-dev python-numpy python-scipy python-matplotlib python-gevent python-pip python-magic python-crypto zip python-dateutil python-mysqldb redis-server autoconf openssl file python git autoconf automake libc-dev libtool python-dev unzip libfreetype6-dev libtaoframework-freetype-cil-dev libxft-dev' returned a non-zero code: 100

Do you have any idea?

**Comment by CrimsonGlory** [comment]
Hi, can you provide us the output of the following commands?
`# docker version`
`# docker-compose --version`
`# docker images`

**Comment by sashlabs-cyber** [comment]
Hi CrimsonGlory,

I came across the same error, and please find the details which you requested.

Regards,

Sai Santosh
![image](https://cloud.githubusercontent.com/assets/13641169/17552706/08c6f534-5f1f-11e6-8c72-1bb3a136925b.png)

**Comment by CrimsonGlory** [comment]
I have the same versions of everything and I can't reproduce the issue.  I think this may be related to [docker](https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/) [dns](https://docs.docker.com/engine/userguide/networking/configure-dns/) config.

Can you try to edit `docker-compose.yml`file and add the following line at the end of the file:

```
  dns: 8.8.4.4
```

The result will look like this:

```
db:
  image: mongo:3.2
  volumes:
    - ../mongo-data/:/data/db

httpd:
    image: httpd:2.4
    volumes:
        - ../codex-frontend/:/usr/local/apache2/htdocs/
    ports:
        - "6100:80"
api:
  build: .
  command: bash -c "(echo updating pip packages && pip install -r /myapp/src/pip_requeriments.txt && echo starting redis && service redis-server start && (echo starting redis worker default && rq worker --path /myapp/src/ default &) && (echo starting redis worker process && rq worker --path /myapp/src/ process &) && (echo starting redis worker checkup && rq worker --path /myapp/src/MalwareCheckUp/ checkup &)) && echo starting api...Check 127.0.0.1:8080 && python /myapp/src/api2.py -H $$HOSTNAME"
  volumes:
    - .:/myapp
  ports:
    - "4500:8080"
  links:
    - db
    - httpd
  dns: 8.8.4.4
```

Then retry:

```
docker-compose up --build
```
